/** CSS custom property names (with `--` prefix) used by @visx/theme. */
export const CSS_VAR_NAMES = {
  chart1: '--chart-1',
  chart2: '--chart-2',
  chart3: '--chart-3',
  chart4: '--chart-4',
  chart5: '--chart-5',
  chart6: '--chart-6',
  chart7: '--chart-7',
  chart8: '--chart-8',
  chart9: '--chart-9',
  chart10: '--chart-10',
  chart11: '--chart-11',
  chart12: '--chart-12',
  chartScaleFrom: '--chart-scale-from',
  chartScaleTo: '--chart-scale-to',
  chartDivergeLow: '--chart-diverge-low',
  chartDivergeMid: '--chart-diverge-mid',
  chartDivergeHigh: '--chart-diverge-high',
  background: '--background',
  card: '--card',
  border: '--border',
  foreground: '--foreground',
  mutedForeground: '--muted-foreground',
  muted: '--muted',
  primary: '--primary',
  destructive: '--destructive',
  chartPositive: '--chart-positive',
  chartNegative: '--chart-negative',
  chartHighlight: '--chart-highlight',
  visxAxisStroke: '--visx-axis-stroke',
  visxAxisTickStroke: '--visx-axis-tick-stroke',
  visxGridStroke: '--visx-grid-stroke',
  visxFontFamily: '--visx-font-family',
} as const;

export const CATEGORICAL_VAR_NAMES: readonly string[] = [
  CSS_VAR_NAMES.chart1,
  CSS_VAR_NAMES.chart2,
  CSS_VAR_NAMES.chart3,
  CSS_VAR_NAMES.chart4,
  CSS_VAR_NAMES.chart5,
  CSS_VAR_NAMES.chart6,
  CSS_VAR_NAMES.chart7,
  CSS_VAR_NAMES.chart8,
  CSS_VAR_NAMES.chart9,
  CSS_VAR_NAMES.chart10,
  CSS_VAR_NAMES.chart11,
  CSS_VAR_NAMES.chart12,
];
